"""
Explanation Synthesis Node.

Takes deterministic engine output (ResidencyDetermination + a list of the
CreditEvaluationResult) and produces a human-readable report for Screen
5/6. Claude's only role is STRICTLY to explain and synthesize it never
authors a status, and its structured-output schema has no field where a
status even could go. The authoritative status per credit is merged back
from the engine's own output after the LLM call, so a hallucinated or
drifted eligibility claim is structurally impossible, not just
discouraged by prompt wording.

The compliance disclaimer is a fixed constant, appended in code, never
generated by the LLM so its exact wording can never vary between calls.
"""

import os
import re
import difflib
from typing import List

from pydantic import BaseModel, Field
from langchain_anthropic import ChatAnthropic

from app.domain.schemas import ResidencyDetermination, CreditEvaluationResult


MANDATORY_DISCLAIMER = (
    "This summary is generated based on the information you provided and "
    "does not constitute tax or legal advice. It does not prepare or file "
    "tax returns. For anything marked 'Needs Documentation,' complex "
    "situations (including dual-status years or joint filing elections), "
    "or before filing, consult a qualified tax professional."
)

SYSTEM_PROMPT = """You are a compliance report writer for a tax preparation \
assistance tool used by international students.

You will be given the OUTPUT of deterministic rules engines: a residency \
determination and a list of credit/deduction evaluations. These have \
ALREADY been decided by Python code implementing IRS and NJ state rules. \
Your job is ONLY to explain these results in plain, accurate language for \
a non-expert reader.

STRICT RULES, you must follow these exactly:
1. You do NOT re-evaluate, reinterpret, upgrade, downgrade, or contradict \
any status or reason given to you. If something is marked INELIGIBLE, \
your explanation must not imply it could still be possible. If something \
is ELIGIBLE, do not add caveats that make it sound uncertain unless the \
provided reason itself says so.
2. Do NOT invent facts, dollar amounts, deadlines, forms, or rules that \
are not present in the data given to you. If the provided reason doesn't \
explain something, say plainly that more detail wasn't available — do not \
guess or fill the gap with outside knowledge.
3. Do NOT give new tax advice, recommendations, or predictions beyond \
restating and clarifying what the engine already determined.
4. Your tone should be clear and reassuring where appropriate, but never \
falsely reassuring — a NEEDS_DOCUMENTATION or INELIGIBLE result should \
read as exactly that, not softened.
5. You are not asked to output a status field — only explanatory text. \
The actual status values are handled separately and will be attached to \
your output afterward; do not restate them as if you were computing them.
6. If multiple credits require the same underlying action (e.g., the same \
election, the same document, the same consultation), write ONE next step \
that names all the affected credits together, rather than repeating the \
same instruction once per credit.
"""


# Hard limits on the LLM call: one bounded request, no stacked retries (the
# graph node wraps the call in its own tenacity retry for transient errors).
LLM_TIMEOUT_SECONDS = float(os.getenv("LLM_TIMEOUT_SECONDS", "30"))
LLM_MODEL = os.getenv("LLM_MODEL", "claude-sonnet-5")
MAX_LLM_FIELD_CHARS = 2000
MAX_NEXT_STEPS = 10


def build_default_llm() -> ChatAnthropic:
    return ChatAnthropic(
        model=LLM_MODEL,
        max_tokens=2000,
        timeout=LLM_TIMEOUT_SECONDS,
        max_retries=0,
    )


def _clip(text: str, limit: int = MAX_LLM_FIELD_CHARS) -> str:
    """LLM output is untrusted: cap its length before storing/returning it."""
    text = text or ""
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


class CreditExplanationOutput(BaseModel):
    """LLM-authored explanation for one credit/deduction, no status field.
    The real status is merged back in code after this is returned."""
    rule_code: str = Field(
        description="The exact rule_code this explanation is about, copied "
        "verbatim from the input data (e.g. 'AOTC', 'NJ_TUITION_DEDUCTION')."
    )
    explanation: str = Field(
        description="Plain-language explanation of this credit's result, "
        "based strictly on the reason text provided."
    )


class ExplanationReportOutput(BaseModel):
    """The LLM's full structured output. No status fields anywhere
    those are merged in from the engine's own data afterward."""
    executive_summary: str = Field(
        description="1-2 sentence plain-language verdict on residency "
        "status and overall credit picture, based only on provided data."
    )
    residency_breakdown: str = Field(
        description="Explanation of the residency determination what "
        "the SPT/exempt-year outcome was and how visa status factored in, "
        "based strictly on the provided audit_trail."
    )
    credit_breakdown: List[CreditExplanationOutput]
    next_steps: List[str] = Field(
        description="Concrete next actions, drawn only from anything "
        "marked NEEDS_DOCUMENTATION in the input, e.g. specific "
        "documents to gather or questions to resolve. Empty list if "
        "nothing requires further action."
    )


class ExplanationReport(BaseModel):
    """Final report returned to the caller,status re-attached from the
    engine's own data, disclaimer appended in code."""
    executive_summary: str
    residency_breakdown: str
    credit_breakdown: List[dict]  # [{rule_code, status, explanation}, ...]
    next_steps: List[str]
    disclaimer: str


def _build_facts_payload(
    residency: ResidencyDetermination,
    credit_evaluations: List[CreditEvaluationResult],
) -> str:
    """Serializes the engine output into a plain-text block the LLM reads
    as its only source of facts."""
    lines = [
        "RESIDENCY DETERMINATION:",
        f"- Status: {residency.status.value}",
        f"- Target form: {residency.target_form}",
        f"- Exempt years used: {residency.exempt_years_used}",
        f"- SPT weighted days: {residency.spt_weighted_days}",
        "- Audit trail:",
    ]
    for step in residency.audit_trail:
        lines.append(f"  - [{step.rule}] passed={step.passed}: {step.details}")

    lines.append("")
    lines.append("CREDIT / DEDUCTION EVALUATIONS:")
    for result in credit_evaluations:
        lines.append(
            f"- rule_code={result.rule_code}, source_type={result.source_type}, "
            f"status={result.status}, estimated_amount={result.estimated_amount}"
        )
        lines.append(f"  reason: {result.reason}")

    return "\n".join(lines)


def _consolidate_next_steps(
    next_steps: List[str],
    rule_codes: List[str],
    similarity_threshold: float = 0.75,
) -> List[str]:
    """
    Deterministic post-processing pass that merges near-identical next
    steps that differ only in which credit they name e.g. one step for
    AOTC and an almost-identical one for LLC, both really describing the
    same underlying action (consult a professional about the same
    6013(g)/(h) election). Uses string similarity after stripping known
    rule_code tokens, rather than a second LLM call, so this stays
    reproducible rather than introducing more non-determinism to fix
    non-determinism.
    """
    next_steps = [_clip(step, 500) for step in next_steps[:MAX_NEXT_STEPS]]
    if len(next_steps) <= 1:
        return next_steps

    def normalize(step: str) -> str:
        text = step
        for code in rule_codes:
            text = re.sub(
                rf"\(?\b{re.escape(code)}\b\)?", "%CREDIT%", text, flags=re.IGNORECASE
            )
        return text

    normalized = [normalize(s) for s in next_steps]
    used = [False] * len(next_steps)
    consolidated: List[str] = []

    for i in range(len(next_steps)):
        if used[i]:
            continue
        group_indices = [i]
        for j in range(i + 1, len(next_steps)):
            if used[j]:
                continue
            ratio = difflib.SequenceMatcher(None, normalized[i], normalized[j]).ratio()
            if ratio >= similarity_threshold:
                group_indices.append(j)
                used[j] = True
        used[i] = True

        if len(group_indices) == 1:
            consolidated.append(next_steps[i])
            continue

        # Find every rule_code actually referenced across the whole group.
        matched_codes = []
        for idx in group_indices:
            for code in rule_codes:
                if re.search(rf"\b{re.escape(code)}\b", next_steps[idx], re.IGNORECASE):
                    if code not in matched_codes:
                        matched_codes.append(code)

        merged_step = normalized[i]
        if matched_codes:
            combined_label = " and ".join(matched_codes)
            merged_step = merged_step.replace("%CREDIT%", combined_label)
        else:
            merged_step = next_steps[i]

        consolidated.append(merged_step)

    return consolidated


def generate_explanation_report(
    residency: ResidencyDetermination,
    credit_evaluations: List[CreditEvaluationResult],
    llm: ChatAnthropic | None = None,
) -> ExplanationReport:
    """
    The explanation-synthesis node. Pure orchestration around a single
    structured-output LLM call, no branching logic, no decisions; the
    graph/route calling this has already decided residency and every
    credit's status via the deterministic engines.
    """
    if llm is None:
        llm = build_default_llm()

    structured_llm = llm.with_structured_output(ExplanationReportOutput)

    facts = _build_facts_payload(residency, credit_evaluations)

    raw_output: ExplanationReportOutput = structured_llm.invoke(
        [
            ("system", SYSTEM_PROMPT),
            ("human", f"Here is the engine output to explain:\n\n{facts}"),
        ]
    )

    # Merge the AUTHORITATIVE status back in from the real engine data,
    # by rule_code. this is what makes a wrong status structurally
    # impossible rather than just prompt-discouraged.
    status_by_rule_code = {r.rule_code: r.status for r in credit_evaluations}

    merged_credit_breakdown = []
    for item in raw_output.credit_breakdown:
        real_status = status_by_rule_code.get(item.rule_code)
        if real_status is None:
            # The LLM referenced a rule_code that doesn't exist in the real
            # data, drop it rather than trust an invented entry.
            continue
        merged_credit_breakdown.append({
            "rule_code": item.rule_code,
            "status": real_status,
            "explanation": _clip(item.explanation),
        })

    return ExplanationReport(
        executive_summary=_clip(raw_output.executive_summary),
        residency_breakdown=_clip(raw_output.residency_breakdown),
        credit_breakdown=merged_credit_breakdown,
        next_steps=_consolidate_next_steps(
            raw_output.next_steps,
            rule_codes=[r.rule_code for r in credit_evaluations],
        ),
        disclaimer=MANDATORY_DISCLAIMER,  # never from the LLM
    )